### PR TITLE
US-2101 Refactor RNS registration screens for better readability and remove circular dependencies

### PR DESCRIPTION
**Pull request by TravellerOnTheRun**
@jormelCoin the job for you is to test that the domain registration works as it was.

### CODE REVIEW

**Review by jormelCoin — CHANGES_REQUESTED** [review]
@TravellerOnTheRun, I was able to create a new RNS and also to put my old RNS. 

Nonetheless, The fee transaction is wrong because is showing up as 0 TRBTC and it should be one in TRBTC and the other one in RIF like it's in production:
Screenshot 2024-02-07 at 10 09 15


Tested relay true

**Comment by jormelCoin** [comment]
@TravellerOnTheRun, Were you able to run the app after rebasing those changes? Because I can't now do it.

I've tried several time both iOs and Android, and I couldn't.

Screenshot 2024-02-07 at 12 14 38

**Comment by TravellerOnTheRun** [comment]
> @TravellerOnTheRun, I was able to create a new RNS and also to put my old RNS.
> 
> Nonetheless, The fee transaction is wrong because is showing up as 0 TRBTC and it should be one in TRBTC and the other one in RIF like it's in production: Screenshot 2024-02-07 at 10 09 15
> 
> Tested relay true

Did you compare it to recent develop?
What is shown in the explorer?

**Comment by jormelCoin** [comment]
> > @TravellerOnTheRun, I was able to create a new RNS and also to put my old RNS.
> > Nonetheless, The fee transaction is wrong because is showing up as 0 TRBTC and it should be one in TRBTC and the other one in RIF like it's in production: Screenshot 2024-02-07 at 10 09 15
> > Tested relay true
> 
> Did you compare it to recent develop? What is shown in the explorer?

Yep, you're right, it shows up the RBTC. Nevertheless, in the development branch, the amount of the transaction that is deducted appears in RIF even though TRBTC appears in the browser, I assume it is because we show the fee charged in rif.

  If you notice on the confirmation screen, you are not charging the 4 RIF that are charged, and they should be charged because this is the relay version, and those 4 RIF are what we should show in the transaction summary.


Evidence of this PR:


https://github.com/rsksmart/rif-wallet/assets/114427184/b3bfc686-e15b-4290-bafa-cd52ea07ca71


Evidence of the latest build

https://github.com/rsksmart/rif-wallet/assets/114427184/08d089a9-8a5b-4018-abcf-c770ef7b63e4



cc: @jessgusclark

**Comment by TravellerOnTheRun** [comment]
> > > @TravellerOnTheRun, I was able to create a new RNS and also to put my old RNS.
> > > Nonetheless, The fee transaction is wrong because is showing up as 0 TRBTC and it should be one in TRBTC and the other one in RIF like it's in production: Screenshot 2024-02-07 at 10 09 15
> > > Tested relay true
> > 
> > 
> > Did you compare it to recent develop? What is shown in the explorer?
> 
> Yep, you're right, it shows up the RBTC. Nevertheless, in the development branch, the amount of the transaction that is deducted appears in RIF even though TRBTC appears in the browser, I assume it is because we show the fee charged in rif.
> 
> If you notice on the confirmation screen, you are not charging the 4 RIF that are charged, and they should be charged because this is the relay version, and those 4 RIF are what we should show in the transaction summary.
> 
> Evidence of this PR:
> 
>  20240208_102944.mp4 
> Evidence of the latest build
> 
>  RPReplay_Final1707401860.MP4 
> cc: @jessgusclark

The thing is that these issues are related to the fact how `activityDeserializer` works with values, since we don't have `etx?.symbol` it assumes `RBTC`, I believe there should be different ticket for that. Let's merge this one, since we have RNS working, and I'll create separate ticket for refactoring `activityDeserializer`, @jessgusclark what do you think? 

@jormelCoin 
Please, retest since I've added the actual calculation of the fee, play around with changing values.

**Comment by TravellerOnTheRun** [comment]
> > > > @TravellerOnTheRun, I was able to create a new RNS and also to put my old RNS.
> > > > Nonetheless, The fee transaction is wrong because is showing up as 0 TRBTC and it should be one in TRBTC and the other one in RIF like it's in production: Screenshot 2024-02-07 at 10 09 15
> > > > Tested relay true
> > > 
> > > 
> > > Did you compare it to recent develop? What is shown in the explorer?
> > 
> > 
> > Yep, you're right, it shows up the RBTC. Nevertheless, in the development branch, the amount of the transaction that is deducted appears in RIF even though TRBTC appears in the browser, I assume it is because we show the fee charged in rif.
> > If you notice on the confirmation screen, you are not charging the 4 RIF that are charged, and they should be charged because this is the relay version, and those 4 RIF are what we should show in the transaction summary.
> > Evidence of this PR:
> > 20240208_102944.mp4
> > Evidence of the latest build
> > RPReplay_Final1707401860.MP4
> > cc: @jessgusclark
> 
> The thing is that these issues are related to the fact how `activityDeserializer` works with values, since we don't have `etx?.symbol` it assumes `RBTC`, I believe there should be different ticket for that. Let's merge this one, since we have RNS working, and I'll create separate ticket for refactoring `activityDeserializer`, @jessgusclark what do you think?
> 
> @jormelCoin Please, retest since I've added the actual calculation of the fee, play around with changing values.

@jormelCoin @jessgusclark 
Forget what I was saying, I found the way of doing it without much refactoring, but the `activityDeserializer` is confusing as hell :(

**Review by jormelCoin — APPROVED** [review]
Functional tests pass

**Review by jessgusclark — APPROVED** [review]

**Pull request merged**
