### PR TITLE
feature/BEV-2131 Will now select medium fee rate or blockbook recomme…

### PR DESCRIPTION
**Pull request by Freshenext**
…nded fee when sending bitcoin.

How to test:
1-Go to send screen
2-Send bitcoin
3-Input address
4-Input amount
5-Click on send
6-The mining fee input should update and be adjusted with the medium rate that you see in that component.

### CODE REVIEW

**Review by jessgusclark — CHANGES_REQUESTED** [review]
Can you rebase this and check it? I'm getting a NaN.toString() error.

**Review by jormelCoin — CHANGES_REQUESTED** [review]
I got this error message:

https://github.com/rsksmart/rif-wallet/assets/114427184/6e1606ae-7191-4a80-b437-3da22b2d2e5b

**Comment by Freshenext** [comment]
Guys remember there is/was a PR that fixed that error: https://github.com/rsksmart/rif-wallet/pull/893

We had to wait until that PR was merged to test this again. 

@jormelCoin @jessgusclark you may go ahead and test again

**Review by jormelCoin — APPROVED** [review]

**Review by jessgusclark — APPROVED** [review]
Thanks! I didn't realize the error was blocking this one.

**Pull request merged**
