### PR TITLE
US-2055 Relay Wallet based on EOA Wallet

### PR DESCRIPTION
**Pull request by TravellerOnTheRun**
Tests I tried:
- [x] Wallet Deploy
- [x] Send RIF, RBTC
- [x] Receive RIF, RBTC
- [x] Import Wallet
- [x] Create Wallet

One thing needs to be done:

- [x]  I see _signTypedData popup when sending, need to figure out why @jessgusclark  I need your help.

### CODE REVIEW

**Review by jessgusclark — CHANGES_REQUESTED** [review]
When I switch to mainnet, it is still using the testnet derivation path to generate the address, in that the testnet and mainnet EOA address is the same. When creating the mainnet address we need to use the correct derivation path of 137, [more information here](https://dev.rootstock.io/rsk/architecture/account-based/). Basically you can test this with [this tool](https://iancoleman.io/bip39/) or use the develop branch and switch to mainnet to see.

**Review by jessgusclark — CHANGES_REQUESTED** [review]
When sending a transaction, in Testnet, the fee is displayed incorrectly. It should be about 2.x RIF, instead iI get this:

Screenshot 2023-12-14 at 5 27 18 PM

Also, after clickingon 'submit' for the transaction nothing happens. There is a console log but the TX is not sent to the relayer.

**Review by jormelCoin — CHANGES_REQUESTED** [review]
As Jesse mentioned, I couldn't submit any tokens either; When I pressed the send button nothing happened.

**Comment by TravellerOnTheRun** [comment]
> When sending a transaction, in Testnet, the fee is displayed incorrectly. It should be about 2.x RIF, instead iI get this:
> 
> Screenshot 2023-12-14 at 5 27 18 PM
> 
> Also, after clickingon 'submit' for the transaction nothing happens. There is a console log but the TX is not sent to the relayer.

Well, that's new... I will investigate

**Comment by TravellerOnTheRun** [comment]
> When sending a transaction, in Testnet, the fee is displayed incorrectly. It should be about 2.x RIF, instead iI get this:
> 
> Screenshot 2023-12-14 at 5 27 18 PM
> 
> Also, after clickingon 'submit' for the transaction nothing happens. There is a console log but the TX is not sent to the relayer.

Reimported the wallet, clean install, it's the same on develop branch @jessgusclark it's urgent!!! I will try again fully deleting everything.

Simulator Screenshot - iPhone 15 - 2023-12-15 at 15 13 16

**Comment by TravellerOnTheRun** [comment]
> > When sending a transaction, in Testnet, the fee is displayed incorrectly. It should be about 2.x RIF, instead iI get this:
> > Screenshot 2023-12-14 at 5 27 18 PM
> > Also, after clickingon 'submit' for the transaction nothing happens. There is a console log but the TX is not sent to the relayer.
> 
> Well, that's new... I will investigate

Apparently it was something on the backend, now it works for me here

https://github.com/rsksmart/rif-wallet/assets/47615361/9fee57f4-b5ac-436f-90d1-f0dc5fd94190

**Comment by TravellerOnTheRun** [comment]
> As Jesse mentioned, I couldn't submit any tokens either; When I pressed the send button nothing happened.

You can try again, apparently there was something happening outside the app

**Review by jormelCoin — CHANGES_REQUESTED** [review]
@TravellerOnTheRun , The issue when sending remains; the steps to reproduce are:
1- build the app
2- Send rif and wait until the pending message disappears.
3- Send rif and wait until the pending message disappears.
4- Send rdoc, in this step, when hitting the send button, does happen nothing.

**Comment by jessgusclark** [comment]
rDOC issue should be fixed but I would like @jormelCoin to test it out again and confirm. I also noticed that the fee is being displayed incorrectly in the Transaction Confirm Screen:

Screenshot 2024-01-05 at 4 29 32 PM


Looking at the network Flipper request it should be around 2.2706 RIF and here it shows 0.2706 RIF. Is it subtracting 2? I'll let you decide if that should be handled in this PR or if you want to create a new ticket for it and handle it in a different one.

**Comment by TravellerOnTheRun** [comment]
> rDOC issue should be fixed but I would like @jormelCoin to test it out again and confirm. I also noticed that the fee is being displayed incorrectly in the Transaction Confirm Screen:
> 
> Screenshot 2024-01-05 at 4 29 32 PM
> 
> Looking at the network Flipper request it should be around 2.2706 RIF and here it shows 0.2706 RIF. Is it subtracting 2? I'll let you decide if that should be handled in this PR or if you want to create a new ticket for it and handle it in a different one.

Identified and fixed the issue.

**Review by jessgusclark — APPROVED** [review]
I have tested this out and I see two issuse. The first is that the RIF price is not showing, I'm not sure if this is an issue here or the EOA wallet so let's handle it in a different ticket.

The second issue is when registering and RNS domain, the second step, we get this error again:
Screenshot 2024-01-08 at 6 15 16 PM

Same error as when sending RDOC. I will need to investigate this furthur this in the library before we go live with it. 

I don't want to block you, so I am going to approve this and make note of these two items to fix.

**Pull request merged**
