### PR TITLE
US-2005 EOA Core Wallet Implementation

### PR DESCRIPTION
**Pull request by TravellerOnTheRun**
Guys, make sure all the features except wallet deployment work(since it's rifRelay specific). I made some adjustments to account for the future changes. I also need to make sure users don't need to re-login. I will apply a check to see if user has a wallet in KMS and extract it to new way of storing the `WalletState`.

You will need to set `use_relay=true` and then run `npx react-native-clean-project`

### CODE REVIEW

**Review by Freshenext — APPROVED** [review]
I like the way this was approached as you decoupled the RIFWallet from many places and only focused on having the "primitive" address value that is required in order to proceed with the processes.

I left one minor change.

I haven't tested it yet in my apps, however the code looks good.

**Review by jormelCoin — CHANGES_REQUESTED** [review]
Hey Alex, I saw two things:

1- When creating a wallet, and press the secure later button; it goes into a loop and displays an error message, it also gets stuck for a couple of seconds.

https://github.com/rsksmart/rif-wallet/assets/114427184/70bf1c39-eb31-4749-b15b-cc38b206195b

2- When importing a wallet, it leads me to another screen different (it goes to the save your phrase screen from the create wallet) 

https://github.com/rsksmart/rif-wallet/assets/114427184/a6d3c956-83e5-435c-9782-46279756cbc9

**Review by jormelCoin — APPROVED** [review]
I was able to:

- Create a wallet (with a inconvenient which was fixed in another PR)
- Import wallet (same comment above)
- Send RIF and RBTC
- Receive RIF
- Create a RNS
- Create a contact

All the above test cases worked as usual.

**Review by jessgusclark — APPROVED** [review]

**Review by jessgusclark — CHANGES_REQUESTED** [review]
I should have caught this before, so sorry for the late notice. The derivation path for mainnet is incorrect, it is using the same one as testnet. You can test this by seeing that the address is the same for mainnet vs testnet. This is incorrect, it should use a different derivation path which would get a different address.

**Comment by jormelCoin** [comment]
@TravellerOnTheRun, I couldn't perform deep tests since I faced this error in both regular Relay and EOA versions. 

https://github.com/rsksmart/rif-wallet/assets/114427184/378b76ea-03fa-405d-8fec-00d5be2afa9a

**Comment by TravellerOnTheRun** [comment]
> @TravellerOnTheRun, I couldn't perform deep tests since I faced this error in both regular Relay and EOA versions.
> 
>  20240123_165812.mp4

@jormelCoin Fixed the error

**Review by jormelCoin — DISMISSED** [review]
These were the things I saw in this PR:

Relay true:
- I was just able to connect via URL and not while scanning. [dapps]
- When I received a transaction from the RIF faucet, I did not see the name "rBTC Faucet" as it is displayed when receiving a rBTC faucet transaction.
- When a transaction is ongoing, and I try to send BTC, I get the usually ongoing alert, but if I press the OK button, I receive an error message.

https://github.com/rsksmart/rif-wallet/assets/114427184/3d6fc9d3-1d14-4c38-852d-61c9ca6afdca

Relay false:
- When creating an RNS, it charges in RBTC, and it's a huge amount.

IMG_7286
- I was unable to record or take screenshot.

**Comment by TravellerOnTheRun** [comment]
> These were the things I saw in this PR:
> 
> Relay true:
> 
> * I was just able to connect via URL and not while scanning. [dapps]
> * When I received a transaction from the RIF faucet, I did not see the name "rBTC Faucet" as it is displayed when receiving a rBTC faucet transaction.
> * When a transaction is ongoing, and I try to send BTC, I get the usually ongoing alert, but if I press the OK button, I receive an error message.
> 
>  RPReplay_Final1706112697.MP4 
> Relay false:
> 
> * When creating an RNS, it charges in RBTC, and it's a huge amount.
> 
> IMG_7286
> 
> * I was unable to record or take screenshot.

- Question regarding scanning: was that Android you tried to scan with? Because I remember we patched scanner for Android, the cause can be different.
- Will check that out
- The error message is not crucial, the thing is you've already moved back to the `HomeScreen` and by pressing 'OK' you're asking to 'GO BACK' from the Navigator and there's no screen to go back to so it throws this error, but it's only in develop

**Comment by TravellerOnTheRun** [comment]
@jormelCoin 
I see rBTC Faucet as a known contact on IOS
Simulator Screenshot - iPhone 15 - 2024-01-25 at 11 33 36
Simulator Screenshot - iPhone 15 - 2024-01-25 at 11 33 51

**Comment by TravellerOnTheRun** [comment]
Screenshot_1706169552
On Android the behaviour is the same

**Comment by TravellerOnTheRun** [comment]
@jormelCoin @jessgusclark 
I believe the RSKRegistrar is incapable of giving price in RBTC, it gives the price in RIF and returns it
```
async register (label: string, owner: string, secret: string, duration: BigNumber, amount: BigNumber, addr?: string): Promise<ContractTransaction> {
      label = validateAndNormalizeLabel(label)
      const _signature = '0x5f7b99d5'
      const _owner = owner.slice(2).toLowerCase()
      const _secret = secret.slice(2)
      const _duration = utils.hexZeroPad(duration.toHexString(), 32).slice(2)
      const _addr = addr ? addr.slice(2).toLowerCase() : _owner
      const _name = Buffer.from(utils.toUtf8Bytes(label)).toString('hex')

      const data = `${_signature}${_owner}${_secret}${_duration}${_addr}${_name}`

      return this.rifToken.transferAndCall(this.fifsAddrRegistrar.address, amount, data)
    }
```

@jessgusclark What would be the solution here? Should we adapt and convert locally or reguest for change in rns-sdk lib? Is that even possible with `EOAWallet` should I disable this feature in EOA?

**Comment by TravellerOnTheRun** [comment]
> @jormelCoin @jessgusclark I believe the RSKRegistrar is incapable of giving price in RBTC, it gives the price in RIF and returns it
> 
> ```
> async register (label: string, owner: string, secret: string, duration: BigNumber, amount: BigNumber, addr?: string): Promise<ContractTransaction> {
>       label = validateAndNormalizeLabel(label)
>       const _signature = '0x5f7b99d5'
>       const _owner = owner.slice(2).toLowerCase()
>       const _secret = secret.slice(2)
>       const _duration = utils.hexZeroPad(duration.toHexString(), 32).slice(2)
>       const _addr = addr ? addr.slice(2).toLowerCase() : _owner
>       const _name = Buffer.from(utils.toUtf8Bytes(label)).toString('hex')
> 
>       const data = `${_signature}${_owner}${_secret}${_duration}${_addr}${_name}`
> 
>       return this.rifToken.transferAndCall(this.fifsAddrRegistrar.address, amount, data)
>     }
> ```
> 
> @jessgusclark What would be the solution here? Should we adapt and convert locally or reguest for change in rns-sdk lib? Is that even possible with `EOAWallet` should I disable this feature in EOA?

I think I found the issue
```
export const useRnsDomainPriceInRif = async (_: string, years: number) => {
  // TODO: re enable this later
  /*const price = await rskRegistrar.price(domain, BigNumber.from(years))
    return utils.formatUnits(price, 18)*/
  if (years < 3) {
    return years * 2
  } else {
    return 4 + (years - 2)
  }
}
```
The price is not calculated dynamically at all and yes, it is in RIF always. It's a change for another PR definetely

```
import {
  DomainRegistrationEnum,
  RnsProcessor,
  useRifToken,
  useRnsDomainPriceInRif as calculatePrice,
} from 'lib/rns'
...

  useEffect(() => {
    calculatePrice(alias, duration).then(setSelectedDomainPrice)
  }, [alias, duration])
```

**Comment by jormelCoin** [comment]
> @jormelCoin I see rBTC Faucet as a known contact on IOS Simulator Screenshot - iPhone 15 - 2024-01-25 at 11 33 36 Simulator Screenshot - iPhone 15 - 2024-01-25 at 11 33 51

@TravellerOnTheRun, my mistake, I forgot to outline the steps. Please go to this website: https://faucet.rifos.org/
and request RIF, you will receive the RIF but the app won't recognize the faucet contact

**Comment by TravellerOnTheRun** [comment]
> https://faucet.rifos.org/

Question: does it show on develop? If not, then it's nothing to do with this PR. Cause it seems from the code, the RIF Faucet is not part of the defaultContacts.

**Comment by jormelCoin** [comment]
> > https://faucet.rifos.org/
> 
> Question: does it show on develop? If not, then it's nothing to do with this PR. Cause it seems from the code, the RIF Faucet is not part of the defaultContacts.

Yep, you're right, it's failing in dev.

**Comment by jessgusclark** [comment]
@jormelCoin and @TravellerOnTheRun 
Regarding RIF price for RNS domains. 

RIF is the only token that the RNS Registration process takes as payment. This can change, but it would be the RNS team to implement such change. 

The fee to send the transaction(s) is paid in rBTC and that could be where the confusion is. But what we are discussing isn't that. 

The price being fixed in the wallet. Yes, I forgot about this piece of tech debt. There is a method in the contract that you can call to get the price. However, it takes a bit of time to return, like 2-3 seconds. So, the +/- buttons looked like they were not incrementing/decrementing. At some point in time, it was determined to hardcode in the price in the wallet so we didn't have to go to the blockchain each time. Was this the right decision? I dunno. We could discuss a better way to handle the UX, perhaps calculate the price at the very end, or something different.

edit: changed mentions at the top, had wrong Alex.

**Comment by jessgusclark** [comment]
@jormelCoin I can't recreate your issue with `USE_RELAY=true` in the .env file.

Screenshot 2024-01-31 at 3 35 02 PM

If I use `USE_RELAY=false` then I do get that error:

Screenshot 2024-01-30 at 6 29 11 PM

---

I'm thinking because the error is in the EOA version then we can create a ticket for it to handle later. This is because right now I want to make sure the Relay version is equal to the current Relay version.

Note that the default `.env` config sets the EOA wallet not Relay wallet.

**Comment by Freshenext** [comment]
When I try to do a transaction, nothing happens:

image

I click on "Confirm" and it just returns that console.log and no more.

I reached Alexander, he'll take a look at it. Let's see if other developers get this error.

**Comment by Freshenext** [comment]
After re-testing the transactions are working properly now. I also tested RNS, and it the transaction successfully.

**Comment by rodrigoncalves** [comment]
This fee should be in tRIF. And the value in dollar is also incorrect. The total send should show 0.00001 RBTC + fees. It also happens for RNS registration.

**Comment by TravellerOnTheRun** [comment]
> This fee should be in tRIF. And the value in dollar is also incorrect. The total send should show 0.00001 RBTC + fees. It also happens for RNS registration.  

Regarding the fee: are you sure you're using relay? If using EOA, then the fee will always be in RBTC. The second problem: is that the first step of RNS Registration? if so, i think it should be 0 because you don't send value the first time around.

**Comment by jessgusclark** [comment]
@rodrigoncalves I can't reproduce that in the Relay version of the wallet, it may exist on the EOA version and if so we will put in a ticket for that.

**Review by jessgusclark — APPROVED** [review]

**Comment by rodrigoncalves** [comment]
> Regarding the fee: are you sure you're using relay? If using EOA, then the fee will always be in RBTC. The second problem: is that the first step of RNS Registration? if so, i think it should be 0 because you don't send value the first time around.

Yes, I added the `USE_RELAY=true` property in `.env` file. Maybe it didn't apply for some reason. Regarding the second problem, for the first step of RNS registration, the amount sent should 0 indeed, however the total send not because I'm still paying the fees.

**Comment by rodrigoncalves** [comment]
Why is the fee like that? o.O

**Review by jessgusclark — APPROVED** [review]

**Pull request merged**
