### PR TITLE
US-1570 - Add Android image and update identifier for Android 

### PR DESCRIPTION
**Pull request by jessgusclark**
- [x] Changes the identifier to a unique one, com.swallet was used
- [x] Adds links to local.property and .keystore files that are not committed into the repo for security reasons
- [x] Icons

### CODE REVIEW

**Comment by jessgusclark** [comment]
Setting this as 'ready' and will put in additional PRs if there are issues.

**Review by TravellerOnTheRun — APPROVED** [review]
Seems you've changed everything successfully

**Comment by jormelCoin** [comment]
@jessgusclark, I noticed that the changes were made in Android, and I couldn't build the app. I got this error message:

Screenshot 2024-01-09 at 15 45 08

**Comment by jessgusclark** [comment]
Commenting for historical reasons. The error @jormelCoin received was unrelated to these changes and was fixed by the team responsible for the failing package (outside IOV). Merged this PR as things worked as expected.

**Pull request merged**
