### PR TITLE
US-2083 EOA Wallet implementation uses the same derivation path for both mainnet and testnet

### PR DESCRIPTION
**Pull request by TravellerOnTheRun**
https://github.com/rsksmart/rif-wallet/assets/47615361/e6924f0b-69da-48ab-931a-5c7f5c265d8d

### CODE REVIEW

**Review by jormelCoin — APPROVED** [review]
I ran the app in develop with a mnemonic. I copied the EOA addresses for mainnet and testnet. Then, I ran Alex’s PR, using the same mnemonic, the addresses in mainnet were exactly. So, it works as expected:

**Comment by jormelCoin** [comment]
However, this is how I see the Android app.

Screenshot 2024-01-09 at 12 50 39

@jessgusclark @TravellerOnTheRun

**Comment by TravellerOnTheRun** [comment]
> However, this is how I see the Android app.
> 
> Screenshot 2024-01-09 at 12 50 39
> 
> @jessgusclark @TravellerOnTheRun

I'll check it out.

**Comment by TravellerOnTheRun** [comment]
> However, this is how I see the Android app.
> 
> Screenshot 2024-01-09 at 12 50 39
> 
> @jessgusclark @TravellerOnTheRun

Apparently this is a separate issue, I see the same on develop. @jessgusclark we need a separate ticket for that. I bet it's just default font color is applied.
Screenshot_1704873022

**Pull request merged**
