### PR TITLE
US-2163 Confirmation screen fails when leaving the app

### PR DESCRIPTION
**Pull request by TravellerOnTheRun**
@jormelCoin 
Closing the request and reloading the app is expected when `gracePeriod` is over.
https://github.com/rsksmart/rif-wallet/assets/47615361/312a80e9-9dec-43ef-92fd-e0208d97e980

### CODE REVIEW

**Review by jormelCoin — CHANGES_REQUESTED** [review]
Hey @TravellerOnTheRun , I got an error alert when I perform the tests:

https://github.com/rsksmart/rif-wallet/assets/114427184/506df41e-4068-43ea-a83d-8efe9cf8a181

**Comment by TravellerOnTheRun** [comment]
> Hey @TravellerOnTheRun , I got an error alert when I perform the tests:
> 
>  20240302_144848.mp4

First of all, this is not a fatal error, since it's just not being able to find the screen with this name because it does not exist if the app is `unlocked`. Second, it's android specific and weird as I just tried and it was showing and now I'm doing the same and it does not show(video attached).  Third, the ticket was about fixing the failing Send flow, now it's not failing and allows to continue, hence I guess we can consider it fixed.
[untitled.webm](https://github.com/rsksmart/rif-wallet/assets/47615361/47ec811c-a3b8-4b0a-8d69-234bec75d3ea)

**Comment by TravellerOnTheRun** [comment]
> 
> > Hey @TravellerOnTheRun , I got an error alert when I perform the tests:
> > 20240302_144848.mp4
> 
> First of all, this is not a fatal error, since it's just not being able to find the screen with this name because it does not exist if the app is `unlocked`. Second, it's android specific and weird as I just tried and it was showing and now I'm doing the same and it does not show(video attached). Third, the ticket was about fixing the failing Send flow, now it's not failing and allows to continue, hence I guess we can consider it fixed. [untitled.webm](https://github.com/rsksmart/rif-wallet/assets/47615361/47ec811c-a3b8-4b0a-8d69-234bec75d3ea)

**Review by jormelCoin — APPROVED** [review]

**Review by jessgusclark — APPROVED** [review]

**Review by jessgusclark — APPROVED** [review]

**Review by jessgusclark — APPROVED** [review]

**Comment by jessgusclark** [comment]
Fixed merge conflict.

**Pull request merged**
